sudo: false

notifications:
  email: false


language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

install:
  - pip install Django pytest pytest-cov

script:
  - python setup.py sdist
  - pip install ./dist/django-readonly-model-*.tar.gz
  - pytest --cov=readonly_model

after_success:
  - codecov
