sudo: false

notifications:
  email: false


language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

install:
  - pip install Django pytest pytest-django pytest-cov codecov

script:
  - pytest --cov=readonly_model tests
  - python setup.py sdist bdist_wheel
  - pip install ./dist/django-readonly-model-*.tar.gz

after_success:
  - codecov
